"""Add sub expiry

Revision ID: 761e9f2cbf76
Revises: 79818514c899
Create Date: 2026-08-20 22:39:33.762671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '761e9f2cbf76'
down_revision: Union[str, Sequence[str], None] = '79818514c899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted ###
    # Autogenerate incorrectly detected several removed tables; keep existing
    # application tables and only add the new subscription columns to `users`.
    op.add_column('users', sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('cancel_at_period_end', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cancel_at_period_end')
    op.drop_column('users', 'subscription_expires_at')
    op.create_table('milestone_reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('milestone_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supervisor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('decision', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['research_milestones.id'], name=op.f('milestone_reviews_milestone_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], name=op.f('milestone_reviews_supervisor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('milestone_reviews_pkey'))
    )
    op.create_index(op.f('ix_milestone_reviews_milestone_id'), 'milestone_reviews', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_milestone_reviews_id'), 'milestone_reviews', ['id'], unique=False)
    op.create_table('research_milestones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latest_review_comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('research_milestones_created_by_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('research_milestones_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('research_milestones_reviewed_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('research_milestones_pkey'))
    )
    op.create_index(op.f('ix_research_milestones_status'), 'research_milestones', ['status'], unique=False)
    op.create_index(op.f('ix_research_milestones_project_id'), 'research_milestones', ['project_id'], unique=False)
    op.create_index(op.f('ix_research_milestones_id'), 'research_milestones', ['id'], unique=False)
    op.create_table('consultation_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requester_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supervisor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('supervisor_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('consultation_requests_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('consultation_requests_requester_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], name=op.f('consultation_requests_supervisor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('consultation_requests_pkey'))
    )
    op.create_index(op.f('ix_consultation_requests_supervisor_id'), 'consultation_requests', ['supervisor_id'], unique=False)
    op.create_index(op.f('ix_consultation_requests_status'), 'consultation_requests', ['status'], unique=False)
    op.create_index(op.f('ix_consultation_requests_start_at'), 'consultation_requests', ['start_at'], unique=False)
    op.create_index(op.f('ix_consultation_requests_requester_id'), 'consultation_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_consultation_requests_project_id'), 'consultation_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_consultation_requests_id'), 'consultation_requests', ['id'], unique=False)
    op.create_index(op.f('ix_consultation_requests_end_at'), 'consultation_requests', ['end_at'], unique=False)
    op.create_table('reading_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('seconds_logged', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('reading_sessions_paper_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('reading_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reading_sessions_pkey'))
    )
    op.create_index(op.f('ix_reading_sessions_id'), 'reading_sessions', ['id'], unique=False)
    # ### end Alembic commands ###
